# Generated by Django 5.2.11 on 2026-02-26 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_band', models.CharField(max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=16, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('total_rounds', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quest_read_app.round')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quest_read_app.session')),
            ],
            options={
                'ordering': ['round_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_component', models.CharField(choices=[('image_color', 'Image Color'), ('scramble', 'Scramble'), ('audio_mismatch', 'Audio Mismatch')], max_length=32)),
                ('selected', models.CharField(max_length=255)),
                ('correct', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quest_read_app.round')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='quest_read_app.session')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
